# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI Script

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run attached_skill unit test
        run: |
          cd flask
          python attached_skill_test.py
      - name: Run course_test unit test
        run: |
          cd flask
          python course_test.py
      - name: Run learning_journey unit test
        run: |
          cd flask
          python learning_journey_test.py
      - name: Run lj_course unit test
        run: |
          cd flask
          python lj_course_test.py
      - name: Run ljps_role unit test
        run: |
          cd flask
          python ljps_role_test.py
      - name: Run registration unit test
        run: |
          cd flask
          python registration_test.py
      - name: Run role_required_skill unit test
        run: |
          cd flask
          python role_required_skill_test.py
      - name: Run role unit test
        run: |
          cd flask
          python role_test.py
      - name: Run skill unit test
        run: |
          cd flask
          python skill_test.py
      - name: Run staff unit test
        run: |
          cd flask
          python staff_test.py
      - name: Run app INTEGRATION test
        run: |
          cd flask
          python app_test.py
